name: Build TWRP Recovery Image
on:
  workflow_dispatch:
    inputs:
      TWRP_MANIFEST_REPO_URL:
        description: The url of the TWRP manifest repo
        required: true
        default: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git
      BRANCH:
        description: The TWRP manifest repo branch to use
        required: true
        default: twrp-12.1
      DEVICE_PATH:
        description: The path to copy the device tree files to
        required: true
        default: /infinix/Infinix-X655C/
      DEVICE_NAME:
        description: The device name
        required: true
        default: Infinix-X655C
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Install repo tool
        run: |
          mkdir ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod u+x ~/bin/repo
      - name: Init TWRP Manifest Repo
        run: |
          mkdir -p $HOME/twrp/device${{ github.event.inputs.DEVICE_PATH }}
          cd $HOME/twrp
          git config --global color.ui true
          ~/bin/repo init --depth=1 -u ${{ github.event.inputs.TWRP_MANIFEST_REPO_URL }} -b ${{ github.event.inputs.BRANCH }}
      - name: Sync TWRP Repo
        run: |
          cd $HOME/twrp
          ~/bin/repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
          ls -al
      - name: Checkout Device Tree
        uses: actions/checkout@v2
        with:
          path: $HOME/twrp/device${{ github.event.inputs.DEVICE_PATH }}
      - name: Compile
        run: |
           cd $HOME/twrp
           export ALLOW_MISSING_DEPENDENCIES=true
           source build/envsetup.sh
           lunch twrp_${{ github.event.inputs.DEVICE_NAME }}-eng
           ls -al
           echo "Building..."
           make -j$(nproc --all) recoveryimage
           make -j$(nproc --all) bootimage
           echo "Build Complete!"
           ls -al $HOME/twrp/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/
      - name: Generate Id
        id: name
        run: echo "NAME=${{ github.event.inputs.DEVICE_NAME }}-$(date +'%Y%m%d')" >> $GITHUB_ENV
      - name: Copy Releases
        run: |
          cp $HOME/twrp/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/recovery.img $HOME/twrp-recovery-$NAME.img
          cp $HOME/twrp/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/boot.img $HOME/twrp-boot-$NAME.img
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            $HOME/twrp-recovery-$NAME.img
            $HOME/twrp-boot-$NAME.img
          name: $NAME
          tag_name: $NAME
          body: Recovery for ${{ github.event.inputs.DEVICE_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
